const API_BASE='https://newsxphere.xtarnet.us.to';
const $=s=>document.querySelector(s), api=(path,options={})=>fetch(`${API_BASE}/api/admin${path}`,{credentials:'include',...options,headers:{'Content-Type':'application/json',...(options.headers||{})}});
const show=(el,text,ok=false)=>{el.hidden=!text;el.textContent=text;el.className=ok?'output success':'output'};
async function check(){const r=await api('/status');if(!r.ok){$('#login-view').hidden=false;$('#app-view').hidden=true;return}$('#login-view').hidden=true;$('#app-view').hidden=false;$('#connection-title').textContent='Backend connected';$('#connection-detail').textContent='Authenticated Worker is ready.'}
$('#login-form').addEventListener('submit',async e=>{e.preventDefault();const r=await api('/login',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(e.target)))});if(r.ok){$('#login-error').textContent='';check()}else $('#login-error').textContent='Login failed. Check your credentials.'});
$('#logout').addEventListener('click',async()=>{await api('/logout',{method:'POST'});location.reload()});$('#refresh-status').addEventListener('click',check);
document.querySelectorAll('[data-tab]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('[data-panel]').forEach(p=>p.hidden=p.dataset.panel!==b.dataset.tab)}));
$('#writer-form').addEventListener('submit',async e=>{e.preventDefault();const out=$('#writer-output');show(out,'Generating…');const r=await api('/generate',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(e.target)))});show(out,r.ok?(await r.text()):'Generation failed. Check Worker configuration.',r.ok)});
$('#github-form').addEventListener('submit',async e=>{e.preventDefault();const r=await api('/github/commit',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(e.target)))});$('#global-status').textContent=r.ok?'Commit created successfully.':'GitHub commit failed.'});
$('#index-form').addEventListener('submit',async e=>{e.preventDefault();const out=$('#index-output');show(out,'Submitting…');const r=await api('/index',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(e.target)))});show(out,r.ok?await r.text():'Indexing request failed. Check Google service-account configuration.',r.ok)});check();
